# Generated by Django 3.1.3 on 2020-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201117_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='orderno',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='status',
            field=models.CharField(default='o', max_length=5),
        ),
    ]
